# Generated by Django 4.1.3 on 2023-03-03 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
