# Generated by Django 4.1.3 on 2023-03-05 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_leaderboard_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
