# Generated by Django 4.1.3 on 2023-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_leaderboard_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="time",
            field=models.DurationField(),
        ),
    ]
