# Generated by Django 4.1.3 on 2023-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_leaderboard_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
