# Generated by Django 4.1.3 on 2023-03-16 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_quiz_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaderboard",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="LeaderBoard",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
